### PR TITLE
Little version cleanups

### PR DESCRIPTION
**Pull request by Vollstrecker**
I lowered the minimum version a bit and removed the version checks. As we require a higher version there's no need to carry compat-code for cmake 3.1 around. Also (not a separate commit) I removed the setting of the new policy, as new it will be set by cmake-minimum_required.

I think not limiting to an old version just to support old systems is a good idea, also I don't see a point in requiring the newest version without using the features it offers is not the best idea. That's why I lowered the version to the highest version it was checked for. If any newer feature is used, this should be adjusted to the needed version.

I also thought about including this as a var from one common file to ease changing of this value for all places, otoh it's maybe not required as the tests won't be generated if the configure failed. I'll leave this open to discussion as I can't check this atm.

### CODE REVIEW

**Comment by Vollstrecker** [comment]
And yes, some tests fail, but this shouldn't be caused by these changes, I just based on a failing master.

**Comment by abdes** [comment]
> And yes, some tests fail, but this shouldn't be caused by these changes, I just based on a failing master.

I'm banging my head against the wall trying to figure out why the windows build on CI fails but it does not fail on my computer... If you have any idea let me know.

**Comment by Vollstrecker** [comment]
Maybe cryptopp/CMakeLists.txt line 1091... iirc you changed the download location. I can't really check atm because on my side the first 18 checks fail as I refuse to use (or install) ninja. I'm going to change this to use CMAKE_GENERATOR as a next step (if you're not in the mood to change it while debugging the current issues).

**Comment by abdes** [comment]
> I'm going to change this to use CMAKE_GENERATOR as a next step (if you're not in the mood to change it while debugging the current issues).

Go ahead...

I need to troubleshoot this issue with windows CI...

**Comment by abdes** [comment]
@Vollstrecker CPM requires 3.14, and I really would like to keep it that way because CPM makes things much simpler for pulling and managing raw CMake dependencies.

Please do not go below 3.14.

**Comment by Vollstrecker** [comment]
k, but to be honest, we use fetchcontent for pulling our source, so I really don't see the point on using another tool for (as it seems) just the tests.The only benefit atm. seems to be the ccache stuff, but there are things like CMAKE_C_COMPILER_LAUNCHER invented for in version 3.4.

**Comment by abdes** [comment]
> k, but to be honest, we use fetchcontent for pulling our source, so I really don't see the point on using another tool for (as it seems) just the tests.The only benefit atm. seems to be the ccache stuff, but there are things like CMAKE_C_COMPILER_LAUNCHER invented for in version 3.4.

Tests are important, and one of the test cases is to validate that we can use the project with CPM.

**Comment by abdes** [comment]
Do we need to keep `cryptopp-cmake.kdev4` under git control?

**Comment by Vollstrecker** [comment]
> Do we need to keep `cryptopp-cmake.kdev4` under git control?

For sure not, one click too much. Fixed

> Tests are important, and one of the test cases is to validate that we can use the project with CPM.

For sure, but what is cpm doing? Basically downloading it and adding add_subdirectory. Exactly like fc does. If it does some extra things like caching and that stuff, that has to be tested at their end.

**Comment by abdes** [comment]
> For sure, but what is cpm doing? Basically downloading it and adding add_subdirectory. Exactly like fc does. If it does some extra things like caching and that stuff, that has to be tested at their end.

One thing that I currently use is CPM's ability to use the local source of cryptopp-cmake to satisfy the dependency on it. A second thing is passing options to the dependency, and there are many other differences:

https://github.com/cpm-cmake/CPM.cmake/issues/135#issuecomment-657530735

**Comment by Vollstrecker** [comment]
k, I'll update that, but to be honest, most features listed there are no benefit. I don't want rant here about it, but the abillity to use different version of a dep can cause much trouble when multiple version define the same targets, plus a nightmare in install. Offline usage is just the same as setting the right options. Version selection isn't even needed here as we use the same source as the one that was built.

**Comment by abdes** [comment]
I dont want to enter into very complicated arguments neither, but I wanna just stick to the #1 rule in this project: it's a hard fork to enable modern cmake, and that's why I made it. I don't wanna start going backward with cmake versions. That's a non-objective of this repo. The objective is to stay close to the latest version of cmake.

I accepted the 3.14, although it's lower than 3.21, which is required for CMakePresets, because I consider that people who use presets are already at the latest version of cmake...

**Comment by abdes** [comment]
Thanks @Vollstrecker

**Comment by Vollstrecker** [comment]
> but I wanna just stick to the Number 1 rule in this project: it's a hard fork to enable modern cmake, and that's why I made it. I don't wanna start going backward with cmake versions.

This is exactly the point why I joined here. But it's a difference to use the latest features (which is a reason to rise the minimum) or to demand the latest version just because it's the latest version.

> I accepted the 3.14, although it's lower than 3.21, which is required for CMakePresets, because I consider that people who use presets are already at the latest version of cmake...

I guess that's a reasonable compromise. I see the advantage in presets for CI (which uses the latest version) where at some points non-default options are needed. For everyday usage I still see reasonable defaults set in CMakeLists.txt the better way.

So thanks for the input, let's hope future decisions can be made as fast as this one.

**Comment by chausner** [comment]
> But it's a difference to use the latest features (which is a reason to rise the minimum) or to demand the latest version just because it's the latest version.

I agree.

> The objective is to stay close to the latest version of cmake.

I am all for going with reasonably modern versions. Still, it's worth keeping in mind that not everybody can even influence the version of CMake installed, or that updating to a newer version requires manual effort (especially when CMake needs to be built from source). So I still think one should carefully think about the pros and cons everytime before the minimum version number is raised. The large majority of users would be thankful, I am sure.

**Comment by noloader** [comment]
> it's worth keeping in mind that not everybody can even influence the version of CMake installed, or that updating to a newer version requires manual effort (especially when CMake needs to be built from source). So I still think one should carefully think about the pros and cons everytime before the minimum version number is raised. The large majority of users would be thankful, I am sure.

Yes, this.

CMake does not build on AIX or Solaris anymore.

And at $dayjob, we just rejected [Defect Dojo](https://github.com/DefectDojo) for vulnerability management because it cannot build on Ubuntu 20, Ubuntu 22, Fedora 36 or Fedora 37. It cost the company that provides Defect Dojo 10's of thousands of dollars in support contracts because the devs wanted to use the latest version of everything.

Not supporting what you find in the field is evil. And in the case of Defect Dojo, it was costly.

**Pull request merged**
