### PR TITLE
Fix omp

### PR DESCRIPTION
**Pull request by Vollstrecker**
Superseedes #34
Fixed and simplified omp detection for homebrewed libopenmp plus testing that stuff.

### CODE REVIEW

**Comment by smessmer** [comment]
Is the plan to just land this or to also land https://github.com/abdes/cryptopp-cmake/pull/34 ? The goal of https://github.com/abdes/cryptopp-cmake/pull/34 is to add `/opt/homebrew/opt` to the path, which this PR doesn't seem to be doing. I would be surprised if this PR worked on Apple Silicon Macs. Were you able to test that?

**Comment by Vollstrecker** [comment]
Should work now also.

**Comment by abdes** [comment]
This does not work with:
```
❯ uname -a
Darwin Abdessattars-MacBook-Pro.local 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:52 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8112 arm64
```

I installed libomp, and it went under `/opt/homebrew/opt`.

```
==> Pouring libomp--15.0.4.arm64_ventura.bottle.tar.gz
==> Caveats
libomp is keg-only, which means it was not symlinked into /opt/homebrew,
because it can override GCC headers and result in broken builds.

For compilers to find libomp you may need to set:
  export LDFLAGS="-L/opt/homebrew/opt/libomp/lib"
  export CPPFLAGS="-I/opt/homebrew/opt/libomp/include"
```

This is the output of the configure I run:

```
❯ cmake .. -D CMAKE_BUILD_TYPE=Debug -G Ninja -D CMAKE_MAKE_PROGRAM=ninja -D USE_CCACHE=ON -D CMAKE_VERBOSE_MAKEFILE=ON -D USE_OPENMP=ON
=> Project : cryptopp v8.7.0 (7fbbe2e27b42)
-- Using ccache (/opt/homebrew/bin/ccache) (via wrapper).
-- CPM: adding package Ccache.cmake@1.2.3 (v1.2.3)
-- Using ccache: /opt/homebrew/bin/ccache
-- downloading/updating cryptopp
-- cryptopp directory found, pulling...
From https://github.com/weidai11/cryptopp
 * branch              master     -> FETCH_HEAD
-- Crypto++ auto fetched at: /Users/abdessattar/Projects/cryptopp-cmake/_build/_deps/cryptopp
-- Adding install integration test: int-install-default
-- Adding install integration test: int-install-prefix
=> Module : cryptopp
-- [cryptopp] CMake version 3.25.0
-- [cryptopp] System Darwin
-- [cryptopp] Processor arm64
-- [cryptopp]     CMAKE_OSX_ARCHITECTURES :
-- [cryptopp] CMAKE_HOST_SYSTEM_PROCESSOR : arm64
-- [cryptopp]      CMAKE_SYSTEM_PROCESSOR : arm64
-- [cryptopp] Target architecture detected as: arm64 -> CRYPTOPP_ARMV8
-- Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES)
-- Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES)
-- Could NOT find OpenMP (missing: OpenMP_C_FOUND OpenMP_CXX_FOUND)
-- OpenMP: Applying workaround for OSX OpenMP with old cmake that doesn't have FindOpenMP
-- OpenMP: Applying workaround for old CMake that doesn't define FindOpenMP using targets
-- [cryptopp] Generating cmake package config files
-- [cryptopp] Generating pkgconfig files
-- [cryptopp] Platform: ARMv8
-- [cryptopp] Compiler definitions:  CRYPTOPP_DATA_DIR="/Users/abdessattar/Projects/cryptopp-cmake/_build/_deps/cryptopp";CRYPTOPP_ARM_NEON_HEADER=1;CRYPTOPP_ARM_ACLE_HEADER=1;CRYPTOPP_DISABLE_ARM_CRC32=1;CRYPTOPP_DISABLE_ARM_PMULL=1
-- [cryptopp] Compiler options:
-- [cryptopp] Build type: Debug
-- Configuring done
CMake Error: install(EXPORT "cryptopp_Targets" ...) includes target "cryptopp" which requires target "OpenMP_TARGET" that is not in any export set.
-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
```

**Comment by abdes** [comment]
> Should work now also.

This ([f00503d](https://github.com/abdes/cryptopp-cmake/pull/39/commits/f00503db7a5a3f25f274baf364f82f1896d9577a)) works.

Please change the commit messages to meet the expectations of `commitlint`. Start with 'fix: ', have a short one line message, an empty line, then details of the commit changes. I use this to automatically generate the changelog 😄

**Comment by abdes** [comment]
@Vollstrecker This is good to go for a squash and merge with a conventional commit compliant message please 😄. I will leave it to you to do the merge... Thanks for your excellent contribution as usual. Thanks @smessmer for your help.

**Comment by Vollstrecker** [comment]
Done, I guess the description should be ok also, but this check doesn't seem to run on merge.

**Comment by abdes** [comment]
It's ok.
I recommend you do the simple steps in https://github.com/abdes/cryptopp-cmake/blob/master/CONTRIBUTING.md#conventional-commits to make your life much easier for future contributions. Your commit messages will be locally listed immediately before you push them.

**Pull request merged**
