### PR TITLE
feature: add building with pem-pack

### LINKED ISSUE #97: Lack of PEM pack support
The new build system currently has no support for the [Crypto++ PEM pack](https://www.cryptopp.com/wiki/PEM_Pack). In the past, to compile Crypto++ with PEM Pack support, you had to copy over the files into the sources folder, which were then included in the build process due to it using GLOB. This is essentially [what the vcpkg package for Crypto++ does](https://github.com/microsoft/vcpkg/blob/master/ports/cryptopp/portfile.cmake#L27) to this day. Since the new script uses a file list instead of a GLOB, would it be possible to optionally include the PEM pack files so Crypto++ can again be compiled with PEM pack support?

A [similar issue is also open at vcpkg](https://github.com/microsoft/vcpkg/issues/31849). It looks like the person who reported it never reported it upstream. Or at least I have yet to see them post here.

### PR DESCRIPTION
**Pull request by Vollstrecker**
fixes: #97 

As requested here the option to compile with pem. There are no test for it as the scripts show it relies on openssh and other external progs to generate test-input.

### CODE REVIEW

**Comment by karaca75** [comment]
@Vollstrecker thanks for the future. I am new to cpp. How should I include the pem.h? When I use `#include <cryptopp/pem.h>` I am getting this error in visual studio (generated from cmakelist) : `can not open source files`. Thanks for the help.

CMakeLists.txt content

```
cmake_minimum_required(VERSION 3.28)
project(CryptoDemo)
set(LIBRARY_NAME CryptoDemoLIB)
set(EXE_NAME CryptoDemo)
add_library(${LIBRARY_NAME} STATIC src/CryptoService.h src/CryptoService.cpp)

include(FetchContent)

message(CHECK_START "Fetching CryptoPP-CMAKE")

set(CRYPTOPP_CMAKE "cryptopp-cmake")
option(CRYPTOPP_USE_PEM_PACK "ON" "ON")
option(CRYPTOPP_BUILD_TESTING "OFF" "OFF")
set(CRYPTOPP_GIT_TAG "master")
 
FetchContent_Declare(
        ${CRYPTOPP_CMAKE}
        GIT_REPOSITORY  https://github.com/abdes/cryptopp-cmake.git
        GIT_TAG         ${CRYPTOPP_GIT_TAG}
)

FetchContent_MakeAvailable(${CRYPTOPP_CMAKE})
target_link_libraries(${LIBRARY_NAME} PRIVATE cryptopp::cryptopp)

add_executable(${EXE_NAME} src/main.cpp)
target_link_libraries(${EXE_NAME} PRIVATE ${LIBRARY_NAME})
```


image

**Comment by Vollstrecker** [comment]
Looks like your chainbuilding. If you always do it like that, you could use a define instead of cryptopp/ and set it to  "${cryptopp-pem_SOURCE_DIR}/". Or you install cryptopp as the headers should be installed with it. But I see no pem.h in the list, just pem_common.h and (without checking) I'm sure that means this file does not exist at all.

**Comment by karaca75** [comment]
thanks for the answer but as I am new to cpp could not understand what should I do? Can you help me with a updated CmakeLists.txt please?  Thanks!

this is what I have currently:

```
cmake_minimum_required(VERSION 3.28)
project(CryptoDemo)
set(LIBRARY_NAME CryptoDemoLIB)
set(EXE_NAME CryptoDemo)
add_library(${LIBRARY_NAME} STATIC src/CryptoService.h src/CryptoService.cpp)

include(FetchContent)

message(CHECK_START "Fetching CryptoPP-CMAKE")

set(CRYPTOPP_CMAKE "cryptopp-cmake")
option(CRYPTOPP_USE_PEM_PACK "ON" "ON")
option(CRYPTOPP_BUILD_TESTING "OFF" "OFF")
set(CRYPTOPP_GIT_TAG "master")
 
FetchContent_Declare(
        ${CRYPTOPP_CMAKE}
        GIT_REPOSITORY  https://github.com/abdes/cryptopp-cmake.git
        GIT_TAG         ${CRYPTOPP_GIT_TAG}
)

FetchContent_MakeAvailable(${CRYPTOPP_CMAKE})
target_link_libraries(${LIBRARY_NAME} PRIVATE cryptopp::cryptopp)

add_executable(${EXE_NAME} src/main.cpp)
target_link_libraries(${EXE_NAME} PRIVATE ${LIBRARY_NAME})
```

**Comment by Vollstrecker** [comment]
No I checked and add pem.h.

You need something like

'target_compile_definitions(foo PRIVATE PEM_PATH="${cryptopp-pem_SOURCE_DIR}")

and your your source your replace cryptopp with PEM_PATH. If you start detecting an installed cryptopp you guard that with #if not defined and set it to cryptopp.

**Comment by karaca75** [comment]
thanks @Vollstrecker I tried the new master but getting this error during cmake configure

```
-- Configuring done (39.8s)
CMake Error at out/_deps/cryptopp-cmake-src/cryptopp/CMakeLists.txt:1376 (add_library):
  Cannot find source file:

    /out/_deps/cryptopp-pem-src/pem.cpp


CMake Error at out/_deps/cryptopp-cmake-src/cryptopp/CMakeLists.txt:1376 (add_library):
  No SOURCES given to target: cryptopp
```

**Comment by karaca75** [comment]
thank you @Vollstrecker but still I could not make it work. Even if I manually add pem.h it is giving error: PEM_Load and PEM_Save is undefined. I don't know what I am missing here

image

**Comment by Vollstrecker** [comment]
To be honest, beside the tip "don'hardcode that path" I can only tell you to find out what's happening. The docs tell us just to compile the files into the lib and that's what has been done.

**Pull request merged**
