### PR TITLE
Follow #40

### PR DESCRIPTION
**Pull request by Naville**

### CODE REVIEW

**Review by abdes — APPROVED** [review]

**Comment by Naville** [comment]
@abdes Could you possibly re-tag 8.7.0? My downstream depends on it

**Comment by abdes** [comment]
> @abdes Could you possibly re-tag 8.7.0? My downstream depends on it

Well, it's a bit problematic to re-tag with the same tag name. 

My understanding is that Git does not (and it should not) change tags behind users back. So if somebody already got the old tag, doing a git pull on cryptopp-cmake shouldn’t just make them overwrite the old one.

The sane principle I usually follow is: people MUST be able to trust their tag-names. This is why, as documented in [README.md](https://github.com/abdes/cryptopp-cmake#versioning-principles), it is possible that we make new tags for `cryptopp-cmake` while keeping the same version of `crypto++` but with a new tag name.

Would that work for you? A new tag `CRYPTOPP_8_7_0_a` for example?

**Comment by Naville** [comment]
or, I purpose a new mechanism if things broken again, basically ``CRYPTOPP_8_7_0_0/1/2/....``, most of the time there is only ``_0`` variant, which we can probably ignore and just use ``CRYPTOPP_8_7_0``

**Comment by abdes** [comment]
@noloader really insisted on exactly `CRYPTOPP_M_m_p` being the initial one for smooth transition from the old project. We can however use `_1/2/3/...` for subsequent ones.

Tag CRYPTOPP_8_7_0_1 incoming...

List of fixes included are documented in #26, none of them introduces any backward incompatibility.

**Comment by abdes** [comment]
Done.
https://github.com/abdes/cryptopp-cmake/releases/tag/CRYPTOPP_8_7_0_1

**Pull request merged**
